# Generated by Django 6.0.1 on 2026-02-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='KizTech', max_length=100)),
                ('hero_name', models.CharField(default='Caleb Ezekiel Hatbwan', max_length=120)),
                ('hero_roles', models.CharField(default='UI/UX Designer, Web Developer, Data Analyst, Mobile Developer', help_text='Comma-separated roles shown in the hero section.', max_length=255)),
                ('hero_description', models.TextField(default="Passionate about creating exceptional digital experiences that blend innovative design with functional development. Let's bring your vision to life.")),
                ('contact_intro', models.TextField(default='Reach out for projects, collaborations, and business inquiries.')),
                ('contact_location', models.CharField(default='Lagos, Nigeria', max_length=255)),
                ('contact_phone', models.CharField(default='+234 0812 866 6531', max_length=50)),
                ('contact_email', models.EmailField(default='calebezekielhatbwan@gmail.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
