# Generated by Django 6.0.1 on 2026-03-01 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_sitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CounterStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='bi bi-emoji-smile', max_length=80)),
                ('value', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('period', models.CharField(max_length=80)),
                ('school', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('period', models.CharField(max_length=80)),
                ('company', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('highlighted_word', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='bi bi-gear', max_length=80)),
                ('link', models.CharField(default='#', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Skill categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('header', 'Header'), ('hero', 'Hero')], default='header', max_length=20)),
                ('platform', models.CharField(max_length=50)),
                ('icon_class', models.CharField(default='bi bi-link-45deg', max_length=80)),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('quote', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='testimonials/')),
                ('highlight', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_badge',
            field=models.CharField(default='Get to Know Me', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_description_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_description_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_email',
            field=models.EmailField(default='calebezekielhatbwan@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_image',
            field=models.FileField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_location',
            field=models.CharField(default='Lagos, Nigeria', max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_name',
            field=models.CharField(default='Caleb Ezekiel Hatbwan', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_phone',
            field=models.CharField(default='+234 0812 866 6531', max_length=50),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_profession',
            field=models.CharField(default='Software Developer', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_resume_label',
            field=models.CharField(default='Download Resume', max_length=60),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_resume_link',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_talk_label',
            field=models.CharField(default="Let's Talk", max_length=60),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_talk_link',
            field=models.CharField(default='#contact', max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_title',
            field=models.CharField(default='Passionate About Creating Digital Experiences', max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_form_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_form_title',
            field=models.CharField(default='Get In Touch', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_section_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_title',
            field=models.CharField(default='Contact', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='footer_brand',
            field=models.CharField(default='iPortfolio', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='footer_text',
            field=models.CharField(default='All Rights Reserved', max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_image',
            field=models.FileField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_primary_button_label',
            field=models.CharField(default='View My Work', max_length=60),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_primary_button_link',
            field=models.CharField(default='#portfolio', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_secondary_button_label',
            field=models.CharField(default='Get In Touch', max_length=60),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_secondary_button_link',
            field=models.CharField(default='#contact', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='portfolio_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='portfolio_title',
            field=models.CharField(default='Portfolio', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_email',
            field=models.EmailField(default='calebezekielhatbwan@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_location',
            field=models.CharField(default='Lagos Nigeria', max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_phone',
            field=models.CharField(default='+234 0812 866 6531', max_length=50),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_profile_image',
            field=models.FileField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='resume_title',
            field=models.CharField(default='Resume', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='services_button_label',
            field=models.CharField(default='View All Services', max_length=60),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='services_button_link',
            field=models.CharField(default='#services', max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='services_heading_line_1',
            field=models.CharField(default='Innovative business', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='services_heading_line_2',
            field=models.CharField(default='performance solutions', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='services_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='services_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='services_title',
            field=models.CharField(default='Services', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='testimonials_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='testimonials_title',
            field=models.CharField(default='Testimonials', max_length=120),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.FileField(upload_to='portfolio/')),
                ('details_url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='portfolio.portfoliocategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeExperiencePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='portfolio.resumeexperience')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('percentage', models.PositiveIntegerField(default=50)),
                ('tooltip', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
